organisations:
- name: 'foo'
  msp: 'foo'
  member:
    login: 'foomember'
    password: 'member'
  ca:
    name: 'cafoo'
    address: 'http://172.25.0.177:7054'
  peers:
    - name: 'peer-foo'
      address: 'grpc://172.25.0.104:7051'
      admin:
        login: 'fooadmin'
        privkey: /opt/blockchain-monitoring/certs/admin/foo/foo-admin-key.pem
        cert:    /opt/blockchain-monitoring/certs/admin/foo/foo-admin-signed.pem

    - name: 'peer-foo-02'
      address: 'grpc://172.25.0.105:7051'
      admin:
        login: 'fooadmin2'
        privkey: /opt/blockchain-monitoring/certs/admin/foo-02/foo-02-admin-key.pem
        cert:    /opt/blockchain-monitoring/certs/admin/foo-02/foo-02-admin-signed.pem

    - name: 'peer-foo-03'
      address: 'grpc://172.25.0.106:7051'
      admin:
        login: 'fooadmin3'
        privkey: /opt/blockchain-monitoring/certs/admin/foo-03/foo-03-admin-key.pem
        cert:    /opt/blockchain-monitoring/certs/admin/foo-03/foo-03-admin-signed.pem

- name: 'bar'
  msp: 'bar'
  member:
    login: 'barmember'
    password: 'member'
  ca:
    name: 'cabar'
    address: 'http://172.25.0.177:7054'
  peers:
    - name: 'peer-bar'
      address: 'grpc://172.25.0.107:7051'
      admin:
        login: 'baradmin'
        privkey: /opt/blockchain-monitoring/certs/admin/bar/bar-admin-key.pem
        cert:    /opt/blockchain-monitoring/certs/admin/bar/bar-admin-signed.pem

channels:
- name: 'pubfoochan'
  msp:
  - 'foo'
  - 'bar'

  endorsers:
  - name: 'peer-foo'
    msp: 'foo'
    address: 'grpc://172.25.0.104:7051'

  - name: 'peer-foo-02'
    msp: 'foo'
    address: 'grpc://172.25.0.105:7051'

  - name: 'peer-foo-03'
    msp: 'foo'
    address: 'grpc://172.25.0.106:7051'

  - name: 'peer-bar'
    msp: 'bar'
    address: 'grpc://172.25.0.107:7051'

  orderers:
  - name: 'foo-orderer'
    msp:
    - 'foo'
    - 'bar'
    address: 'grpc://172.25.0.102:7050'

  events:
  - name: 'ev-peer-foo'
    msp: 'foo'
    address: 'grpc://172.25.0.104:7053'

  - name: 'ev-peer-foo-02'
    msp: 'foo'
    address: 'grpc://172.25.0.105:7053'

  - name: 'ev-peer-foo-03'
    msp: 'foo'
    address: 'grpc://172.25.0.106:7053'

  - name: 'ev-peer-bar'
    msp: 'bar'
    address: 'grpc://172.25.0.107:7053'

  chaincodes:
  - name: 'prettycode'
    path: 'github.xyz/thebestcode/prettycode'
    version: '1.0'
